"""delete_column_price_discount_table_product

Revision ID: 2892ed7cc0b8
Revises: a0466b293779
Create Date: 2025-03-13 23:14:24.637655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2892ed7cc0b8'
down_revision: Union[str, None] = 'a0466b293779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
