"""add_column_user_order_id

Revision ID: 39f1a5ef3ee2
Revises: 247d49f73a2d
Create Date: 2025-03-13 13:55:19.274570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f1a5ef3ee2'
down_revision: Union[str, None] = '247d49f73a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_order_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'user_order_id')
    # ### end Alembic commands ###
