"""order_add_column_total_price

Revision ID: 449464a4536b
Revises: 8c4c31aa388c
Create Date: 2025-02-20 16:31:53.759558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449464a4536b'
down_revision: Union[str, None] = '8c4c31aa388c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_price')
    # ### end Alembic commands ###
