"""delete_microsecond_created_at

Revision ID: 620df2b9a210
Revises: 0b7f261c1cc8
Create Date: 2025-03-12 16:38:01.370085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620df2b9a210'
down_revision: Union[str, None] = '0b7f261c1cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
