"""add_column_size_id_size_name_table_order_item

Revision ID: e0fb4020d597
Revises: 2892ed7cc0b8
Create Date: 2025-03-14 01:05:57.117806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fb4020d597'
down_revision: Union[str, None] = '2892ed7cc0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('size_id', sa.Integer(), nullable=False))
    op.add_column('order_item', sa.Column('size_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'size_name')
    op.drop_column('order_item', 'size_id')
    # ### end Alembic commands ###
