"""delete_column_auth_type

Revision ID: 7ef13faa1d14
Revises: 2c6a1fa06c82
Create Date: 2025-02-26 10:22:36.266085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef13faa1d14'
down_revision: Union[str, None] = '2c6a1fa06c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'auth_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('auth_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
