"""init_table

Revision ID: abd1c9bb7d55
Revises: 7a6c8cec9b02
Create Date: 2025-02-13 16:12:21.533012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd1c9bb7d55'
down_revision: Union[str, None] = '7a6c8cec9b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_item_product_id_fkey', 'order_item', type_='foreignkey')
    op.drop_constraint('order_item_order_id_fkey', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_item', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('order_item_order_id_fkey', 'order_item', 'order', ['order_id'], ['id'])
    op.create_foreign_key('order_item_product_id_fkey', 'order_item', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
