name: CI (Test and Docker build and push)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_name
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.0"

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Запуск тестов с pytest
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          SERVER_HOST: app
          SERVER_PORT: 8000
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SECRET_KEY_ADMIN: ${{ secrets.SECRET_KEY_ADMIN }}
          SECRET_KEY_EMAIL: ${{ secrets.SECRET_KEY_EMAIL }}
          SECRET_KEY_BOT: ${{ secrets.SECRET_KEY_BOT }}
          S3_HOST: ${{ secrets.S3_HOST }}
          S3_BACKET: ${{ secrets.S3_BACKET }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_HOST: postgres
          DB_PORT: 5432
          DB_NAME: test_name
          REDIS_HOST: redis
          REDIS_PORT: 6379
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          RMQ_HOST: rabbitmq
          RMQ_PORT: 5672
          RMQ_PLAGIN_PORT: 15672
          RMQ_USER: ${{ secrets.RMQ_USER }}
          RMQ_PASSWORD: ${{ secrets.RMQ_PASSWORD }}
        run: pytest -c pytest.ini -v

      - name: Проверка кода с flake8
        run: |
          pip install flake8
          flake8 . --count --max-line-length=80 --statistics --config=tests/.flake8

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Вход в Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Сборка и пуш Docker образа
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fastfood-api:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastfood-api:latest